### PR TITLE
Issue #2 - Intellij file

### PR DESCRIPTION
**Pull request by pecota-luizalabs**

### CODE REVIEW

**Comment by gabrielguaiato-luizalabs** [comment]
:+1:

**Comment by pecota-luizalabs** [comment]
@agrava-luizalabs could you merge this pr?

**Comment by agrava-luizalabs** [comment]
Not yet, I need to check the rules you've set and see if everything is working as expected

**Comment by agrava-luizalabs** [comment]
@eduardomartins-luizalabs You have added two files:

``` sh
$ setup/luizalabs.xml
$ setup/intellij/luizalabs.xml
```

I suppose that you've only intended to add one file, which one of them is the correct one? You also have to update the README file, there you are saying something about a `.jar`.

Will we have some file with a self install? If not, you could give directions on how to add this file properly on IntelliJ.

**Comment by pecota-luizalabs** [comment]
I will do a .sh to install, i will close this PR right now and make that.

**Comment by agrava-luizalabs** [comment]
Ok, no problem

**Pull request closed without merging**
